# Generated by Django 3.2.4 on 2021-06-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_reg_number',
            new_name='student_admission_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_mobile',
            new_name='student_phone_number',
        ),
    ]
