# Generated by Django 3.2.4 on 2021-06-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210604_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_admission_number',
        ),
    ]
