# Generated by Django 3.2.4 on 2021-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_student_student_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
